---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1654529/public.html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R Audio $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R sass $DEPLOYPATH
